-- ============================================================
-- VOTING SYSTEM — POSTGRESQL / SUPABASE SCHEMA
-- Run once in the Supabase SQL Editor on a fresh database.
-- Re-runnable: every statement is guarded.
--
-- Replaces database_setup.sql + migration.sql, which are MySQL-only
-- (AUTO_INCREMENT / ENUM / TINYINT / INSERT IGNORE / USE) and cannot
-- run here.
--
-- DESIGN NOTE — why SMALLINT and not BOOLEAN for the flag columns:
-- the PHP layer writes and compares these as integers, e.g.
--   WHERE is_admin = 0          (admin/index.php, index.php)
--   SET is_verified = 1         (admin/voters.php)
--   SET is_active = 1 - is_active   (admin/announcements.php)
-- Postgres BOOLEAN rejects `= 0` with "operator does not exist:
-- boolean = integer", and `1 - is_active` has no boolean equivalent.
-- SMALLINT behaves identically on MySQL and Postgres, so the same PHP
-- runs unchanged against both. Values are constrained to 0/1 below.
-- ============================================================

-- Optional clean slate. Uncomment only if you want to wipe existing data.
-- DROP TABLE IF EXISTS votes, announcements, candidates, elections, voters, constituencies CASCADE;

-- ── 1. CONSTITUENCIES ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS constituencies (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    state       VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── 2. VOTERS ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS voters (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_id        VARCHAR(20)  NOT NULL UNIQUE,
    username        VARCHAR(50)  NOT NULL UNIQUE,
    full_name       VARCHAR(150),
    email           VARCHAR(100) NOT NULL UNIQUE,
    phone           VARCHAR(20),
    dob             DATE,
    gender          VARCHAR(10) CHECK (gender IN ('male','female','other')),
    address         TEXT,
    state           VARCHAR(100),
    district        VARCHAR(100),
    constituency_id INTEGER REFERENCES constituencies(id) ON DELETE SET NULL,
    photo           VARCHAR(255),
    is_verified     SMALLINT NOT NULL DEFAULT 0 CHECK (is_verified IN (0,1)),
    is_admin        SMALLINT NOT NULL DEFAULT 0 CHECK (is_admin IN (0,1)),
    password        VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── 3. ELECTIONS ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS elections (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200) NOT NULL,
    description     TEXT,
    start_date      TIMESTAMP NOT NULL,
    end_date        TIMESTAMP NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','upcoming','active','completed')),
    show_results    SMALLINT NOT NULL DEFAULT 0 CHECK (show_results IN (0,1)),
    constituency_id INTEGER REFERENCES constituencies(id) ON DELETE SET NULL,
    created_by      INTEGER REFERENCES voters(id)         ON DELETE SET NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── 4. CANDIDATES ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS candidates (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    party           VARCHAR(100) NOT NULL,
    party_logo      VARCHAR(255),
    symbol          VARCHAR(255),
    constituency_id INTEGER REFERENCES constituencies(id) ON DELETE SET NULL,
    election_id     INTEGER REFERENCES elections(id)      ON DELETE SET NULL,
    age             INTEGER CHECK (age IS NULL OR age BETWEEN 18 AND 120),
    education       VARCHAR(200),
    bio             TEXT,
    manifesto       TEXT,
    status          VARCHAR(10) NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active','inactive')),
    photo           VARCHAR(255),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── 5. VOTES ─────────────────────────────────────────────────
-- The UNIQUE constraint is load-bearing: vote.php relies on catching the
-- resulting PDOException to block a double vote under a race.
CREATE TABLE IF NOT EXISTS votes (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    election_id  INTEGER NOT NULL REFERENCES elections(id)   ON DELETE CASCADE,
    voter_id     INTEGER NOT NULL REFERENCES voters(id)      ON DELETE CASCADE,
    candidate_id INTEGER NOT NULL REFERENCES candidates(id)  ON DELETE CASCADE,
    voted_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_voter_election UNIQUE (voter_id, election_id)
);

-- ── 6. ANNOUNCEMENTS ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS announcements (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(200) NOT NULL,
    body       TEXT NOT NULL,
    type       VARCHAR(10) NOT NULL DEFAULT 'info'
                   CHECK (type IN ('info','success','warning','danger')),
    is_active  SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_by INTEGER REFERENCES voters(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── 7. INDEXES ───────────────────────────────────────────────
-- Every results/dashboard page runs correlated COUNT(*) subqueries over
-- votes filtered by candidate_id + election_id.
CREATE INDEX IF NOT EXISTS idx_votes_candidate_election ON votes (candidate_id, election_id);
CREATE INDEX IF NOT EXISTS idx_votes_election           ON votes (election_id);
CREATE INDEX IF NOT EXISTS idx_votes_voter              ON votes (voter_id);
CREATE INDEX IF NOT EXISTS idx_candidates_election      ON candidates (election_id);
CREATE INDEX IF NOT EXISTS idx_candidates_constituency  ON candidates (constituency_id);
CREATE INDEX IF NOT EXISTS idx_candidates_status        ON candidates (status);
CREATE INDEX IF NOT EXISTS idx_voters_constituency      ON voters (constituency_id);
CREATE INDEX IF NOT EXISTS idx_elections_status_window  ON elections (status, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_announcements_active     ON announcements (is_active, created_at DESC);

-- ── 8. SEED: CONSTITUENCIES ──────────────────────────────────
INSERT INTO constituencies (id, name, state) VALUES
    (1, 'Delhi North',     'Delhi'),
    (2, 'Mumbai South',    'Maharashtra'),
    (3, 'Bangalore East',  'Karnataka'),
    (4, 'Chennai Central', 'Tamil Nadu'),
    (5, 'Kolkata West',    'West Bengal')
ON CONFLICT (id) DO NOTHING;

-- ── 9. SEED: SAMPLE ELECTION ─────────────────────────────────
INSERT INTO elections (id, title, description, start_date, end_date, status, show_results) VALUES
    (1,
     'General Assembly Election 2025',
     'Annual general assembly election for all constituencies.',
     CURRENT_TIMESTAMP - INTERVAL '1 day',
     CURRENT_TIMESTAMP + INTERVAL '6 days',
     'active',
     0)
ON CONFLICT (id) DO NOTHING;

-- ── 10. SEED: SAMPLE CANDIDATES ──────────────────────────────
INSERT INTO candidates (name, party, constituency_id, election_id, status)
SELECT v.name, v.party, v.cons_id, 1, 'active'
FROM (VALUES
    ('Rahul Sharma', 'National Party',    1),
    ('Priya Patel',  'People''s Alliance', 2),
    ('Amit Verma',   'Progressive Front', 3),
    ('Sunita Rao',   'Democratic Union',  4),
    ('Vikram Singh', 'National Party',    5)
) AS v(name, party, cons_id)
WHERE NOT EXISTS (
    SELECT 1 FROM candidates c WHERE c.name = v.name AND c.election_id = 1
);

-- ── 11. SEED: SAMPLE ANNOUNCEMENT ────────────────────────────
INSERT INTO announcements (title, body, type, is_active)
SELECT 'General Assembly Election 2025 is Now Open',
       'Voting is now open for the General Assembly Election 2025. All registered voters can cast their vote until the election closes.',
       'success', 1
WHERE NOT EXISTS (
    SELECT 1 FROM announcements
    WHERE title = 'General Assembly Election 2025 is Now Open'
);

-- ── 12. RESYNC IDENTITY SEQUENCES ────────────────────────────
-- Required because sections 8–9 inserted explicit ids, which does not
-- advance the identity sequence. Without this the next INSERT from the
-- admin panel fails with a duplicate-key error on id.
SELECT setval(pg_get_serial_sequence('constituencies', 'id'), COALESCE((SELECT MAX(id) FROM constituencies), 1));
SELECT setval(pg_get_serial_sequence('elections',      'id'), COALESCE((SELECT MAX(id) FROM elections),      1));
SELECT setval(pg_get_serial_sequence('candidates',     'id'), COALESCE((SELECT MAX(id) FROM candidates),     1));
SELECT setval(pg_get_serial_sequence('announcements',  'id'), COALESCE((SELECT MAX(id) FROM announcements),  1));
SELECT setval(pg_get_serial_sequence('voters',         'id'), COALESCE((SELECT MAX(id) FROM voters),         1));
SELECT setval(pg_get_serial_sequence('votes',          'id'), COALESCE((SELECT MAX(id) FROM votes),          1));

-- ============================================================
-- AFTER THIS SCRIPT: create your admin account.
-- 1. Register normally through the site's /register.php form.
-- 2. Then run, with your username:
--      UPDATE voters SET is_admin = 1, is_verified = 1 WHERE username = 'yourusername';
-- Do not insert an admin row by hand — the password column must hold a
-- PHP password_hash() value, which only the register form produces.
-- ============================================================
